export const ResponseStatusCode = Object.freeze({
	OK: 200,
	CREATED: 201,
	ACCEPTED: 202,
	NO_CONTENT: 204,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	METHOD_NOT_ALLOWED: 405,
	CONFLICT: 409,
	UNPROCESSABLE_ENTITY: 422,
	INTERNAL_SERVER_ERROR: 500,
	BAD_GATEWAY: 502,
});

export const ResponseStatus = Object.freeze({
	// 2xx
	OK: { CODE: ResponseStatusCode.OK, MESSAGE: 'SUCCESS' },
	CREATED: { CODE: ResponseStatusCode.CREATED, MESSAGE: 'CREATED' },
	ACCEPTED: { CODE: ResponseStatusCode.ACCEPTED, MESSAGE: 'ACCEPTED' },
	NO_CONTENT: { CODE: ResponseStatusCode.NO_CONTENT, MESSAGE: 'NO_CONTENT' },

	// 4xx
	BAD_REQUEST: { CODE: ResponseStatusCode.BAD_REQUEST, MESSAGE: 'BAD_REQUEST' },
	TOO_MANY_FILES: { CODE: ResponseStatusCode.BAD_REQUEST, MESSAGE: 'TOO_MANY_FILES' },
	FILE_SIZE_TOO_LARGE: { CODE: ResponseStatusCode.BAD_REQUEST, MESSAGE: 'FILE_SIZE_TOO_LARGE' },
	TOKEN_EXPIRED: { CODE: ResponseStatusCode.UNAUTHORIZED, MESSAGE: 'TOKEN_EXPIRED' },
	TOKEN_INVALID: { CODE: ResponseStatusCode.UNAUTHORIZED, MESSAGE: 'TOKEN_INVALID' },
	TOKEN_STEALING: { CODE: ResponseStatusCode.UNAUTHORIZED, MESSAGE: 'TOKEN_STEALING' },
	UNAUTHORIZED: { CODE: ResponseStatusCode.UNAUTHORIZED, MESSAGE: 'UNAUTHORIZED' },
	FORBIDDEN: { CODE: ResponseStatusCode.FORBIDDEN, MESSAGE: 'FORBIDDEN' },
	NOT_FOUND: { CODE: ResponseStatusCode.NOT_FOUND, MESSAGE: 'NOT_FOUND' },
	METHOD_NOT_ALLOWED: { CODE: ResponseStatusCode.METHOD_NOT_ALLOWED, MESSAGE: 'METHOD_NOT_ALLOWED' },
	CONFLICT: { CODE: ResponseStatusCode.CONFLICT, MESSAGE: 'CONFLICT' },
	UNPROCESSABLE_ENTITY: { CODE: ResponseStatusCode.UNPROCESSABLE_ENTITY, MESSAGE: 'UNPROCESSABLE_ENTITY' },

	// 5xx
	INTERNAL_SERVER_ERROR: { CODE: ResponseStatusCode.INTERNAL_SERVER_ERROR, MESSAGE: 'INTERNAL_SERVER_ERROR' },
	FILE_UPLOAD_ERROR: { CODE: ResponseStatusCode.INTERNAL_SERVER_ERROR, MESSAGE: 'FILE_UPLOAD_ERROR' },
	BAD_GATEWAY: { CODE: ResponseStatusCode.BAD_GATEWAY, MESSAGE: 'BAD_GATEWAY' },
});